# Phase 3 creates deployments for shard 1 (root)
#
# helm upgrade \
#  --install \
#  --values ./hack/kind-values-phase3.yaml \
#  --namespace kcp-alpha \
#  --create-namespace \
#  alpha ./charts/kcp
#
fullnameOverride: alpha
externalHostname: "kcp.dev.test"
etcd:
  enabled: true
kcp:
  externalLogicalClusterAdminFlag: true
  tag: main
  enabled: true
  v: 8
  tokenAuth:
    enabled: true
  batteries:
    - workspace-types
    - metrics-viewer
  extraFlags:
    - --feature-gates=WorkspaceMounts=true
  homeWorkspaces:
    enabled: true
externalCache:
  enabled: true
  cacheInternalHostname: "cache-cache.kcp-cache.svc"
sharding:
  enabled: true
  isRoot: true
caBundle:
  enabled: false
  configMapName: kcp.dev.test
  configMapKey: root-certs.pem
oidc:
  enabled: true
  issuerUrl: https://idp.dev.local:6443
  clientId: kcp-dev
  groupClaim: groups
  usernameClaim: email
  usernamePrefix: kcp-dev-idp-
  groupsPrefix: kcp-dev-idp-
  caSecretName: dex-pki-ca
