{{- if .Values.certificates.cache.certs -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cache.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "cache"
spec:
  secretName: {{ include "cache.fullname" . }}-cert
  duration: 8760h # 365d
  renewBefore: 360h # 15d
  {{- with .Values.certificates.subject }}
  subject:
    {{- toYaml . | nindent 4 }}
  {{ end}}
  privateKey:
    {{- toYaml .Values.certificates.privateKeys | nindent 4 }}
  usages:
    - server auth
  dnsNames:
    {{- range .Values.certificates.dnsNames }}
    - {{ . }}
    {{- end }}
  issuerRef:
    {{- if .Values.certificates.cache.certificateIssuer }}
    {{ .Values.certificates.cache.certificateIssuer | toYaml | nindent 4 }}
    {{- else }}
    name: {{ include "certificates.cache" . }}-server-issuer
    kind: Issuer
    {{- end }}
{{- if .Values.certificates.secretTemplate.enabled }}
  secretTemplate:
{{- if .Values.certificates.secretTemplate.annotations }}
    annotations:
    {{- toYaml .Values.certificates.secretTemplate.annotations | nindent 6 }}
{{- end }}
{{- if .Values.certificates.secretTemplate.labels }}
    labels:
    {{- toYaml .Values.certificates.secretTemplate.labels | nindent 6 }}
{{- end }}
{{- end }}

{{- end }}
