# Phase 4 creates deployments for shard 1
#
# helm upgrade \
#  --install \
#  --values ./hack/kind-values-phase3.yaml \
#  --namespace kcp-alpha \
#  --create-namespace \
#  alpha ./charts/kcp
#
fullnameOverride: beta
externalHostname: "kcp-beta.dev.local"
etcd:
  enabled: true
kcp:
  enabled: true
  tag: main
  batteries:
    - workspace-types
    - metrics-viewer
kcpFrontProxy:
  enabled: true
certificates:
  name: certs
  kcp:
    pki: false
    certs: false
  frontproxy:
    pki: false
    certs: false
  etcd:
    pki: false
    certs: false
  secretTemplate:
    enabled: false
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "kcp-beta"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "kcp-beta"
