{{- if .Values.kcpFrontProxy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frontproxy.fullname" . }}-kubeconfig
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: system:admin
        cluster:
          # this references the CA certificate that signed kcp's serving certificate
          # (kcp-server-issuer by default)
          certificate-authority: /etc/kcp/tls/ca/tls.crt
          server: "https://{{ include "kcp.fullname" . }}:6443"
    contexts:
      - name: system:admin
        context:
          cluster: system:admin
          user: admin
    current-context: system:admin
    users:
      - name: admin
        user:
          client-certificate: /etc/kcp-front-proxy/kubeconfig-client-cert/tls.crt
          client-key: /etc/kcp-front-proxy/kubeconfig-client-cert/tls.key
{{- end }}
