{{- if .Values.kine.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kine.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: "kine"
spec:
  secretName: {{ include "kine.fullname" . }}-cert
  duration: 8760h # 365d
  renewBefore: 360h # 15d
  {{- with .Values.certificates.subject }}
  subject:
    {{- toYaml . | nindent 4 }}
  {{- end}}
  privateKey:
    {{- toYaml .Values.certificates.privateKeys | nindent 4 }}
  usages:
    - server auth
    - client auth  # required because kine uses this cert for calls to itself
  dnsNames:
    - {{ include "kine.fullname" . }}
  ipAddresses:
    - 0.0.0.0
  issuerRef:
    name: {{ include "kine.fullname" . }}-pki
{{- end }}
